name: Format and List

on:
  pull_request:
    types:
      - opened

jobs:
  format_and_lint:
    name: Format and Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 18
          
      - name: Install Dependencies
        run: pnpm install

      - name: Format Code
        run: pnpm format

      - name: Lint Code
        run: pnpm lint-run