name: Format and Lint with pnpm

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  format_and_lint:
    name: Format and Lint Code with pnpm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Format Code
        run: pnpm format

      - name: Lint Code
        run: pnpm lint-run
