interface Env {
  DB: D1Database;
  FIREBASE_API_KEY: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
  FIREBASE_MESSAGING_SENDER_ID: string;
  FIREBASE_APP_ID: string;
  FIREBASE_VAPID_SERVER_KEY: string;
  GOOGLE_APPLICATION_CREDENTIALS_JSON: string;
}
